import type { Metadata } from 'next';
import './globals.css';
import Header from './components/main-route/Header';
import Footer from './components/main-route/Footer';

export const metadata: Metadata = {
  title: 'Rest Client App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
