import type { Metadata } from 'next';
import './globals.css';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import Footer from '../components/main-route/Footer/Footer';
import Header from '../components/main-route/Header/Header';
import ErrorBoundary from '../components/error-boundary/ErrorBoundary';

export const metadata: Metadata = {
  title: 'Rest Client App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider>
          <Header />
          <ErrorBoundary> {children}</ErrorBoundary>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
